name: notify main changes
on:
    push:
        branches:
            - 'main'
env:
    MIRROR_URL: git@github.com:EpitechPGE3-2025/G-SVR-500-RUN-5-1-survivor-4.git
jobs:
    push_to_mirror:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: mirroring
                uses: pixta-dev/repository-mirroring-action@v1
                with:
                    target_repo_url:
                        ${{ env.MIRROR_URL }}
                    ssh_private_key:
                        ${{ secrets.GIT_SSH_PRIVATE_KEY }}